### ISSUE TITLE
Suggestion:  Alternative http server

### ISSUE THREAD

**Issue by mikekidder** [jarsbe/react-simple#2]
I'd recommend something besides `python -m SimpleHTTPServer` to serve up React

Many Windows users do not have Python installed.

Something like: puer, or http-server?

**Comment by jackcallister** [comment]
Yeah good call. Ideally I would like to just serve this from the file system but since file:// is not an allowed protocol on the fbcdn it must run through a server. I'll first have a look through other CDNs which freely expose React and ReactDOM as globals.

**Comment by mastilver** [comment]
Or Tèsèvè if you don't want to deal with cli: https://teseve.github.io/

**Comment by battaile** [comment]
I like the http-server suggestion, that is what I am using for this.

**Comment by jackcallister** [comment]
@battaile @mastilver Cheers for these suggestions, I'll get them in the readme. I'd like to keep a `package.json` file out of the project as I believe NPM and CLI tools are beyond the scope for the target audience.

**Comment by jackcallister** [comment]
The only thing preventing serving the site from the file system is that the babel compilation cannot be run through the file protocol.
