### ISSUE TITLE
Easiest way to add components in new files?

### ISSUE THREAD

**Issue by battaile** [jarsbe/react-simple#3]
Everything works great for me here as long as I keep everything in script.js.  My problem is that once I move components into their own files, I'm stuck.  

I'm used to using the import/export syntax enabled by transpilers but that doesn't work (which makes sense as it would defeat the purpose of simplicity).   My next thought was perhaps I could either just include the component files as text/babel or text/js and things would just work, but no dice there either.  I then started down a long winding path of polyfills, combining approaches, and other generally bad ideas that lead me to believe there was probably some way easier way and I should perhaps just ask.

**Comment by mastilver** [comment]
I'm using the global `window` to expose components: https://github.com/mastilver/react-simple/tree/multiple-files

**Comment by battaile** [comment]
Ah, good call, thanks!

**Comment by battaile** [comment]
Cool... https://github.com/jarsbe/react-simple/pull/4

**Comment by jackcallister** [comment]
Cheers @mastilver I've taken your advice and added a minimal amount of code in #4 for users to get set up.
